name: base
channels:
  - nvidia
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=*=*cuda12.1*
  - pytorch-cuda=12.1
  - pytorch3d
  - pip
  - pip:
    - numpy
    - git+https://github.com/nghorbani/configer
#    - git+https://github.com/nghorbani/human_body_prior
    - -r requirements.txt
#   - mediapipe
#   - opencv-python
#   - wandb